#!/usr/bin/env node
/**
 * praxis-init.js — zero-cost scaffolding for a target project.
 *
 * Scans an existing repository, detects its stack, and generates a minimal
 * starter Praxis layer: CLAUDE.md (Claude Code) and AGENTS.md (OpenCode &
 * other agents), a starter skill index reference, working memory, and a
 * curated core-skills symlink/copy list.
 *
 * Usage: node <praxis-root>/scripts/praxis-init.js [target-dir]
 */
const fs = require('fs');
const path = require('path');
const { fileURLToPath } = require('url');

const praxisRoot = path.resolve(path.dirname(__filename), '..');
const target = path.resolve(process.argv[2] || process.cwd());

if (!fs.existsSync(target)) {
  console.error(`Target directory not found: ${target}`);
  process.exit(1);
}

// ---- stack detection -------------------------------------------------------
function detectStack(dir) {
  const stack = [];
  const has = f => fs.existsSync(path.join(dir, f));
  const read = f => { try { return fs.readFileSync(path.join(dir, f), 'utf8'); } catch { return ''; } };

  if (has('package.json')) {
    const pkg = read('package.json');
    if (/react/.test(pkg)) stack.push('React');
    if (/vue/.test(pkg)) stack.push('Vue');
    if (/@angular\/core/.test(pkg)) stack.push('Angular');
    if (/next/.test(pkg)) stack.push('Next.js');
    if (/vitest|jest/.test(pkg)) stack.push('Vitest/Jest');
    if (/typescript/.test(pkg) || has('tsconfig.json')) stack.push('TypeScript');
    if (!stack.length) stack.push('Node.js');
  }
  if (has('composer.json')) {
    const cj = read('composer.json');
    stack.push(/laravel/.test(cj) ? 'Laravel' : 'PHP');
  }
  if (has('requirements.txt') || has('pyproject.toml')) {
    stack.push(/django/.test(read('requirements.txt') + read('pyproject.toml')) ? 'Django' : 'Python');
  }
  if (has('go.mod')) stack.push('Go');
  if (has('Cargo.toml')) stack.push('Rust');
  if (has('docker-compose.yml') || has('compose.yml')) stack.push('Docker Compose');
  return stack;
}

// ---- recommended skills per detected stack ---------------------------------
function recommendSkills(stack) {
  const recs = ['tdd', 'debugging', 'planning', 'code-review', 'verification'];
  if (stack.includes('Laravel') || stack.includes('PHP')) recs.push('api-design', 'database-design');
  if (stack.some(s => ['React', 'Vue', 'Angular', 'Next.js'].includes(s)))
    recs.push('frontend-ui-engineering', 'accessibility-compliance');
  if (stack.includes('Docker Compose')) recs.push('devops-pipelines');
  if (stack.includes('Go') || stack.includes('Rust')) recs.push('system-architecture');
  return [...new Set(recs)];
}

const stack = detectStack(target);
const skills = recommendSkills(stack);

console.log(`Praxis init -> ${target}`);
console.log(`Detected stack: ${stack.length ? stack.join(', ') : 'unknown'}`);
console.log(`Recommended core skills: ${skills.join(', ')}\n`);

// ---- generate files ---------------------------------------------------------
const rel = p => path.relative(target, p).replace(/\\/g, '/');
const skillTable = skills.map(s =>
  `| [\`${s}\`](${rel(path.join(praxisRoot, 'skills', s, 'SKILL.md'))}) | see file |`
).join('\n');

const header = `<!-- Generated by NassAI-Praxis praxis-init on ${new Date().toISOString().slice(0, 10)} -->
`;

const guidance = `${header}
# Project Guidance (NassAI-Praxis)

## Stack

${stack.length ? stack.map(s => `- ${s}`).join('\n') : '- (not detected — edit this section)'}

## Shared Knowledge (Single Source of Truth)

Skills, personas, agents, and methodology live in the master NassAI-Praxis
repository at \`${praxisRoot}\` — do NOT copy them into this project.
Improvements made there apply here automatically.

## Skill Loading Protocol

1. Consult the Praxis skill index at \`${rel(path.join(praxisRoot, 'PRAXIS.md'))}\`.
2. Load ONLY the skills whose triggers match the current task. Advisory
   context budget: ~8K tokens of Praxis content per task by default —
   adjust for host, model, and context window.
3. Recommended starting skills for this project:

| Skill | Notes |
|-------|-------|
${skillTable}

## Memory (project-owned)

This project's memory lives in \`memory/\` — reads AND writes stay here,
never in the master repo:

- Working: \`memory/working/current.md\` — update at session end.
- Episodic: \`memory/episodic/YYYY-MM-DD.md\` — record outcomes and lessons.
- Semantic: \`memory/semantic/conventions.md\` — project conventions.

## Methodology

TDD first (RED-GREEN-REFACTOR), small atomic commits, security-first,
human-reviewed evolution. Full methodology: \`${rel(path.join(praxisRoot, 'AGENTS.md'))}\`.

To activate in OpenCode: say "use praxis" in a session.`;

const results = [];
function writeIfAbsent(dest, content, label) {
  try {
    if (fs.existsSync(dest)) {
      results.push(`  SKIPPED  ${label} (already exists - left unchanged)`);
      return;
    }
    fs.writeFileSync(dest, content, 'utf8');
    results.push(`  CREATED  ${label}`);
  } catch (err) {
    results.push(`  FAILED   ${label} (${err.message})`);
  }
}

for (const name of ['CLAUDE.md', 'AGENTS.md']) {
  writeIfAbsent(path.join(target, name), guidance, name);
}

// starter project-local memory (matches plugin's local-memory resolution:
// <project>/memory/ takes precedence over the master repo's memory dir)
const memDir = path.join(target, 'memory', 'working');
fs.mkdirSync(path.join(target, 'memory', 'semantic'), { recursive: true });
fs.mkdirSync(path.join(target, 'memory', 'episodic'), { recursive: true });
fs.mkdirSync(memDir, { recursive: true });
writeIfAbsent(path.join(memDir, 'current.md'),
`# Working Context
- Project: ${path.basename(target)}
- Current Task: none
- Last Action: Praxis initialized
- Next Step: start first task
- Blockers: none
`, 'memory/working/current.md');
writeIfAbsent(path.join(target, 'memory', 'semantic', 'conventions.md'),
`version: "1.0.0"
created: "${new Date().toISOString().slice(0, 10)}"

# Project Conventions

(Seed this file with this project's actual conventions as they are established.)
`, 'memory/semantic/conventions.md');

console.log('\nSummary:');
for (const line of results) console.log(line);
const failed = results.filter(r => r.startsWith('  FAILED')).length;
if (failed) console.error(`\n${failed} operation(s) FAILED - review the output above.`);

console.log(`
Next steps:
1. REVIEW the generated/skipped files listed above before committing them.
2. Generated skill links point into this Praxis clone at:
   ${praxisRoot}
   If you move or delete that clone, regenerate these files.
3. Open CLAUDE.md (Claude Code) or AGENTS.md (OpenCode) to activate.`);
