#!/usr/bin/env node
/**
 * praxis-init.js — zero-cost scaffolding for a target project.
 *
 * Scans an existing repository, detects its stack, and generates a minimal
 * starter Praxis layer: CLAUDE.md (Claude Code) and AGENTS.md (OpenCode &
 * other agents), a starter skill index reference, working memory, and a
 * curated core-skills symlink/copy list.
 *
 * Usage: node <praxis-root>/scripts/praxis-init.js [target-dir]
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const praxisRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const target = path.resolve(process.argv[2] || process.cwd());

if (!fs.existsSync(target)) {
  console.error(`Target directory not found: ${target}`);
  process.exit(1);
}

// ---- stack detection -------------------------------------------------------
function detectStack(dir) {
  const stack = [];
  const has = f => fs.existsSync(path.join(dir, f));
  const read = f => { try { return fs.readFileSync(path.join(dir, f), 'utf8'); } catch { return ''; } };

  if (has('package.json')) {
    const pkg = read('package.json');
    if (/react/.test(pkg)) stack.push('React');
    if (/vue/.test(pkg)) stack.push('Vue');
    if (/@angular\/core/.test(pkg)) stack.push('Angular');
    if (/next/.test(pkg)) stack.push('Next.js');
    if (/vitest|jest/.test(pkg)) stack.push('Vitest/Jest');
    if (/typescript/.test(pkg) || has('tsconfig.json')) stack.push('TypeScript');
    if (!stack.length) stack.push('Node.js');
  }
  if (has('composer.json')) {
    const cj = read('composer.json');
    stack.push(/laravel/.test(cj) ? 'Laravel' : 'PHP');
  }
  if (has('requirements.txt') || has('pyproject.toml')) {
    stack.push(/django/.test(read('requirements.txt') + read('pyproject.toml')) ? 'Django' : 'Python');
  }
  if (has('go.mod')) stack.push('Go');
  if (has('Cargo.toml')) stack.push('Rust');
  if (has('docker-compose.yml') || has('compose.yml')) stack.push('Docker Compose');
  return stack;
}

// ---- recommended skills per detected stack ---------------------------------
function recommendSkills(stack) {
  const recs = ['tdd', 'debugging', 'planning', 'code-review', 'verification'];
  if (stack.includes('Laravel') || stack.includes('PHP')) recs.push('api-design', 'database-design');
  if (stack.some(s => ['React', 'Vue', 'Angular', 'Next.js'].includes(s)))
    recs.push('frontend-ui-engineering', 'accessibility-compliance');
  if (stack.includes('Docker Compose')) recs.push('devops-pipelines');
  if (stack.includes('Go') || stack.includes('Rust')) recs.push('system-architecture');
  return [...new Set(recs)];
}

const stack = detectStack(target);
const skills = recommendSkills(stack);

console.log(`Praxis init -> ${target}`);
console.log(`Detected stack: ${stack.length ? stack.join(', ') : 'unknown'}`);
console.log(`Recommended core skills: ${skills.join(', ')}\n`);

// ---- generate files ---------------------------------------------------------
const rel = p => path.relative(target, p).replace(/\\/g, '/');
const skillTable = skills.map(s =>
  `| [\`${s}\`](${rel(path.join(praxisRoot, 'skills', s, 'SKILL.md'))}) | see file |`
).join('\n');

const header = `<!-- Generated by NassAI-Praxis praxis-init on ${new Date().toISOString().slice(0, 10)} -->
`;

const guidance = `${header}
# Project Guidance (NassAI-Praxis)

## Stack

${stack.length ? stack.map(s => `- ${s}`).join('\n') : '- (not detected — edit this section)'}

## Skill Loading Protocol

1. Consult the Praxis skill index at \`${rel(path.join(praxisRoot, 'PRAXIS.md'))}\`.
2. Load ONLY the skills whose triggers match the current task (budget ~8K tokens).
3. Recommended starting skills for this project:

| Skill | Notes |
|-------|-------|
${skillTable}

## Memory

- Working memory: \`.praxis/memory/working.md\` — update at session end.
- Episodic logs: \`.praxis/episodic/YYYY-MM-DD.md\` — record outcomes and lessons.

## Methodology

TDD first (RED-GREEN-REFACTOR), small atomic commits, security-first,
human-reviewed evolution. Full methodology: \`${rel(path.join(praxisRoot, 'AGENTS.md'))}\`.
`;

for (const name of ['CLAUDE.md', 'AGENTS.md']) {
  const dest = path.join(target, name);
  if (fs.existsSync(dest)) {
    console.log(`  skip ${name} (exists)`);
    continue;
  }
  fs.writeFileSync(dest, guidance, 'utf8');
  console.log(`  wrote ${name}`);
}

// starter memory
const memDir = path.join(target, '.praxis', 'memory');
const workFile = path.join(memDir, 'working.md');
if (!fs.existsSync(workFile)) {
  fs.mkdirSync(memDir, { recursive: true });
  fs.writeFileSync(workFile,
`# Working Context
- Project: ${path.basename(target)}
- Current Task: none
- Last Action: Praxis initialized
- Next Step: start first task
- Blockers: none
`, 'utf8');
  console.log('  wrote .praxis/memory/working.md');
} else {
  console.log('  skip .praxis/memory/working.md (exists)');
}

console.log(`
Done. Open ${target}/CLAUDE.md in Claude Code or ${target}/AGENTS.md in
OpenCode to activate. Re-run praxis-build.js in the Praxis repo after
editing any skill.`);
